path = r"c:\EGWallet\src\i18n\translations.ts"
with open(path, encoding="utf-8") as f:
    content = f.read()

ZH_BLOCK = """  // -- 新键 (简体中文) --
  'common.back': '返回',
  'common.done': '完成',
  'common.notAuthenticated': '未认证',
  'common.networkError': '网络错误，请重试。',
  'common.serverUnreachable': '无法连接到服务器。',
  'common.areYouSure': '您确定吗？',
  'common.justNow': '刚刚',
  'common.minsAgo': '分钟前',
  'common.hoursAgo': '小时前',
  'common.daysAgo': '天前',
  'auth.enterEmail': '请输入您的电子邮件',
  'auth.enterPassword': '请输入密码',
  'auth.passwordTooShort': '密码至少需要8个字符',
  'auth.accountCreated': '账户创建成功！',
  'auth.signUpError': '注册错误',
  'auth.signInError': '登录错误',
  'auth.checkCredentials': '请检查您的凭据并重试',
  'auth.emailPlaceholder': 'your@example.com',
  'auth.passwordPlaceholder': '输入密码',
  'auth.passwordHint': '至少8个字符',
  'auth.termsAgreement': '继续即表示您同意我们的服务条款和隐私政策',
  'send.selectSourceWallet': '选择来源钱包',
  'send.enterValidAmount': '请输入有效金额',
  'send.enterDestWalletId': '输入收款钱包ID',
  'send.enterCardNumber': '输入卡号',
  'send.enterCardExpiry': '输入到期日',
  'send.enterCardholderName': '输入持卡人姓名',
  'send.enterBankName': '输入银行名称',
  'send.enterAccountNumber': '输入账户号码',
  'send.enterAccountHolderName': '输入账户持有人姓名',
  'send.bankWithdrawal': '银行取款',
  'send.payNow': '立即支付',
  'send.transactionFailed': '交易失败',
  'send.backendUnavailable': '服务暂不可用，请重试。',
  'send.scamWarningSigns': '诈骗警告',
  'send.reviewTransaction': '审核交易',
  'send.reviewWithdrawal': '审核取款',
  'send.payingFrom': '付款来自',
  'send.mobileOperator': '移动运营商',
  'send.accountLabel': '账户',
  'send.phoneLabel': '电话',
  'send.youWithdraw': '您提取',
  'send.senderCurrency': '汇款方货币',
  'send.yourCurrency': '您的货币',
  'send.youReceive': '您收到',
  'send.confirmAndSend': '确认并发送',
  'send.confirmWithdrawal': '确认取款',
  'send.transferSubtitle': '将资金转至其他钱包',
  'send.withdrawSubtitle': '提现到银行账户',
  'send.loadingWallets': '正在加载钱包...',
  'send.recipientPlaceholder': '钱包ID 或 @用户名',
  'send.intlFeeHint': '手续费：1.75% - 海外银行账户',
  'send.localFeeHint': '手续费：1.28% - 本地银行或移动支付',
  'send.bankDays': '3至5个工作日',
  'send.paymentSentToast': '付款已发送',
  'send.scamWarningText': '请勿向您不认识的人转账。',
  'send.withdrawalFeeInfo': '提现将收取手续费',
  'send.fxFeeInfo': '适用1.15%的外汇手续费',
  'send.sameCurrencyFree': '同币种转账免费，无手续费。',
  'settings.couldNotSetUsername': '无法设置用户名',
  'settings.usernameSetTitle': '用户名已设置',
  'settings.usernameSetMessage': '您的标识已保存',
  'settings.deleteAccountConfirmFull': '您确定要删除账户吗？',
  'settings.accountDeletionTitle': '账户删除',
  'settings.accountDeletionMessage': '请联系客服以删除您的账户。',
  'settings.bugReportSubtitle': '描述出现的问题。',
  'settings.bugDescribePlaceholder': '描述问题...',
  'settings.bugSend': '发送',
  'settings.describeBugIssue': '请描述问题。',
  'settings.currencyUpdated': '货币已更新',
  'settings.languageUpdated': '语言已更新',
  'settings.languageUpdatedMessage': '应用语言已更新',
  'settings.autoConvertOnDesc': '自动转换所有收款',
  'settings.autoConvertOffDesc': '以原始货币接收付款。',
  'settings.autoConvertEnabled': '自动转换已启用',
  'settings.autoConvertDisabled': '自动转换已禁用',
  'settings.faceLock': '面部锁定',
  'settings.fingerprintLock': '指纹锁定',
  'settings.faceLockSubtitle': '解锁需要面部识别',
  'settings.fingerprintLockSubtitle': '解锁需要指纹',
  'settings.faceIdSubtitle': '通过面部或指纹解锁',
  'settings.biometricEnabled': '生物识别锁定已启用',
  'settings.biometricDisabled': '生物识别锁定已禁用',
  'settings.setUsernameTitle': '设置用户名',
  'settings.usernameModalSubtitle': '其他人可以通过您的标识向您转账',
  'settings.usernamePlaceholder': '您的名称',
  'settings.currencyModalDesc': '如果未自动检测到，请手动选择您的货币。',
  'settings.searchCurrencyPlaceholder': '搜索货币或国家...',
  'settings.currencyHelpText2': '货币不正确？点击上方选择其他货币。',
  'receipt.addedTo': '已添加至',
  'receipt.walletId': '钱包ID',
  'receipt.senderCurrency': '汇款方货币',
  'receipt.transferFee': '转账手续费',
  'receipt.fxRate': '汇率',
  'receipt.dateTime': '日期和时间',
  'receipt.reference': '参考号',
  'receipt.status': '状态',
  'receipt.recipientCurrency': '收款方货币',
  'qrScan.invalidQrTitle': '无效的QR码',
  'qrScan.invalidQrMessage': '此QR码不属于EGWallet。',
  'qrScan.unsupportedQrTitle': '不支持的QR',
  'qrScan.unsupportedQrMessage': '此类型的QR码不受支持。',
  'qrScan.qrExpiredTitle': 'QR已过期',
  'qrScan.qrExpiredMessage': '此付款QR已过期，请申请新的。',
  'qrScan.walletLoadError': '无法加载您的钱包，请重试。',
  'qrScan.missingWalletId': '此QR码不包含收款钱包ID。',
  'qrScan.invalidQrAmount': '此QR码包含无效金额。',
  'qrScan.missingQrCurrency': '此QR码不包含货币。',
  'qrScan.invalidAmount': '请输入大于0的有效金额。',
  'qrScan.missingCurrency': '请输入货币。',
  'qrScan.cantPayYourself': '您无法向自己付款。',
  'qrScan.paymentSentTitle': '付款已发送',
  'qrScan.paymentSentMsg': '您的付款已成功发送。',
  'qrScan.somethingWentWrong': '出了点问题，请重试。',
  'qrScan.payViaQr': '通过QR付款',
  'qrScan.expired': '已过期',
  'qrScan.expiresIn': '过期时间',
  'qrScan.validFor': '有效期约',
  'qr.requestTimeout': '请求超时，请重试。',
  'qr.contactSupportError': '如果问题持续，请联系客服。',
  'kyc.cameraPermission': '相机权限',
  'kyc.cameraPermissionMsg': '请允许访问相机以拍摄您的证件。',
  'kyc.galleryPermission': '相册权限',
  'kyc.galleryPermissionMsg': '请允许访问相册以上传证件。',
  'kyc.invalidDocType': '无效证件类型',
  'kyc.invalidDocTypeMsg': '不接受此类型的证件。',
  'kyc.invalidFileType': '无效文件格式',
  'kyc.invalidFileTypeMsg': '仅接受JPEG、PNG和WEBP图片。',
  'kyc.invalidImage': '无效图片',
  'kyc.invalidImageMsg': '无法读取所选图片，请尝试其他图片。',
  'kyc.fileTooLarge': '文件过大',
  'kyc.fileTooLargeMsg': '请选择小于10MB的图片。',
  'kyc.documentSubmittedTitle': '证件已提交',
  'kyc.documentSubmittedMsg': '我们的团队将在1至2个工作日内审核您的证件。',
  'kyc.documentCaptured': '证件已拍摄',
  'kyc.documentCapturedMsg': '照片已保存，点击上传发送。',
  'kyc.uploadFailed': '上传失败',
  'kyc.takePhoto': '拍照',
  'kyc.chooseFromGallery': '从相册选择',
  'kyc.idCardInstructions': '将证件放在平整的表面上，确保四角清晰可见。',
  'kyc.passportInstructions': '打开护照到照片页，照片和号码必须清晰可读。',
  'kyc.driversLicenseInstructions': '将驾照放在平整表面，照片和号码必须清晰可读。',
  'kyc.proofOfAddressInstructions': '上传最近3个月内的账单或官方信函。',
  'kyc.dailyLimitsTitle': '每日交易限额',
  'kyc.dailySendingLimit': '每日发送限额（美元）',
  'kyc.dailyLimitDesc': '这是您在24小时内可发送的最高金额。',
  'kyc.walletCapacityTitle': '钱包容量',
  'kyc.maxBalance': '最大余额：250,000美元',
  'kyc.walletCapacityDesc': '您的钱包不能超过此金额。',
  'kyc.feesTitle': '费用和收费',
  'kyc.feesDisclaimer': '所有费用在确认前显示，无隐藏收费。',
  'kyc.regionalInfoTitle': '地区信息',
  'kyc.regionGQ': '赤道几内亚',
  'kyc.regionAF': '非洲',
  'kyc.regionGlobal': '全球',
  'kyc.regionLabel': '地区：',
  'kyc.primaryCurrency': '主要货币：',
  'budget.enterValidAmount': '请输入有效金额',
  'budget.createBudgetTitle': '创建预算',
  'budget.createAction': '创建',
  'budget.noBudgets': '暂无预算',
  'budget.noBudgetsDesc': '点击+创建每月支出限额',
  'budget.perMonth': '/月',
  'budget.currencyLabel': '货币',
  'budget.budgetCreated': '预算已创建',
  'budget.budgetSaved': '预算已保存',
  'card.createVirtualCardTitle': '创建虚拟卡',
  'card.createVirtualCardMsg': '创建用于在线购物的新虚拟卡',
  'card.createAction': '创建',
  'card.freezeConfirmMsg': '冻结此虚拟卡？',
  'card.unfreezeConfirmMsg': '解冻此虚拟卡？',
  'card.cardCreated': '虚拟卡已创建',
  'trusted.removeTitle': '移除设备',
  'trusted.removeMessage': '您确定要移除此设备吗？',
  'trusted.removedTitle': '已移除',
  'trusted.removedMsg': '设备已移除',
  'trusted.trustedTitle': '已信任',
  'trusted.trustedMsg': '设备已标记为受信任',
  'biometric.title': 'EGWallet已锁定',
  'biometric.touchFingerprint': '触摸指纹传感器以解锁',
  'biometric.lookAtDevice': '注视设备以解锁',
  'biometric.authenticate': '验证身份以解锁',
  'biometric.unlock': '解锁',
  'biometric.footer': '您的钱包受生物识别认证保护',
  'dispute.selectTxError': '请选择要申诉的交易',
  'dispute.describeError': '请描述问题',
  'dispute.minCharsError': '请至少提供10个字符来描述问题',
  'dispute.submittedTitle': '申诉已提交',
  'dispute.submittedMsg': '您的申诉已提交审核。',
  'dispute.sendEmailButton': '发送邮件给客服',
  'dispute.doneButton': '完成',
  'dispute.emailFailedTitle': '打开邮件失败',
  'dispute.emailFailedMsg': '请手动联系 support@egwallet.com',
  'dispute.sentToSupport': '申诉将发送至我们的客服团队。',
  'dispute.txTypeSend': '发送',
  'dispute.txTypeReceive': '接收',
  'dispute.txTypeWithdrawal': '提现',
  'dispute.aiSuggestion.unauthorized': '检查您的登录活动并修改密码。',
  'dispute.aiSuggestion.wrongAmount': '核实适用的汇率和手续费。',
  'dispute.aiSuggestion.notReceived': '确认钱包ID正确，并查看您的所有余额。',
  'dispute.aiSuggestion.duplicate': '检查交易记录中是否有相似金额。',
  'dispute.aiSuggestion.other': '详细描述您的问题，包括交易ID和金额。',
  'payRequest.invalidLink': '无效的付款链接。',
  'payRequest.loadError': '无法加载此请求，请检查网络后重试。',
  'payRequest.loginRequired': '需要登录',
  'payRequest.loginMsg': '请登录以完成此付款。',
  'payRequest.logIn': '登录',
  'payRequest.noWallet': '未找到钱包，请重试。',
  'payRequest.paymentSentTitle': '付款已发送！',
  'payRequest.paymentSentMsg': '付款已成功完成。',
  'payRequest.paymentFailed': '付款失败',
  'payRequest.couldNotProcess': '无法处理付款。',
  'deposit.missingBankFields': '请填写所有银行字段。',
  'deposit.missingCardFields': '请填写所有卡片字段，包括CVC。',
  'deposit.tooSmall': '请输入有效的存款金额。',
  'deposit.sessionExpired': '您的会话已过期，请重新登录。',
  'deposit.serviceUnavailable': '无法连接到服务器，请重试。',
  'deposit.depositSubmitted': '您的付款正在处理中。',
  'deposit.addBankAccount': '添加银行账户',
  'deposit.addCreditCard': '添加信用卡',
  'deposit.addDebitCard': '添加借记卡',
  'deposit.choosePaymentMethod': '选择支付方式',
  'deposit.selectedSuffix': '（已选）',
  'deposit.stripeAvailable': 'Stripe可用 - 真实卡片支付已启用。',
  'deposit.demoMode': '演示模式 - 不会扣除真实费用。',
  'request.requestSentToast': '请求已发送',
  'request.sentTitle': '请求已发送',
  'request.sentMsg': '您的请求已成功发送。',
  'request.missingFirstName': '请输入名字。',
  'request.missingLastName': '请输入姓氏。',
  'request.invalidEmail': '请输入有效的电子邮件地址。',
  'request.employeeAddedTitle': '员工已添加',
  'request.employeeAddedMsg': '员工已添加到您的团队。',
  'request.selectEmployee': '请先选择员工。',
  'request.invalidAmount': '请输入有效金额。',
  'request.confirmPayrollTitle': '确认薪资请求',
  'request.sendRequestBtn': '发送请求',
  'request.payrollSentMsg': '付款请求已发送。',
  'request.cancelRequestTitle': '取消请求',
  'request.noteOptionalLabel': '备注（可选）',
  'request.notePlaceholder': '这是用来做什么的？',
  'request.statusPending': '待处理',
  'request.statusPaid': '已支付',
  'request.statusCancelled': '已取消',
  'report.enterTitle': '请输入标题',
  'report.describeTheProblem': '请描述问题',
  'report.submittedTitle': '报告已提交',
  'report.submittedWithTicket': '感谢！我们的团队将在24小时内审核您的报告。',
  'report.submittedNoTicket': '感谢您的反馈！',
  'report.submitFailed': '提交报告失败，请重试。',
  'employer.registerRequired': '公司名称和税号为必填项',
  'employer.registrationSuccess': '公司已注册并通过验证！',
  'employer.registrationSuccessDemo': '公司已注册！',
  'employer.walletFunded': '钱包已充值',
  'employer.walletFundedMsg': '已添加至您的资金钱包。',
  'employer.walletFundedDemo': '钱包已充值',
  'employer.employeeEmailRequired': '员工电子邮件为必填项',
  'employer.employeeAdded': '员工已添加到薪资名单。',
  'employer.employeeAddedDemo': '员工已添加',
  'employer.noEmployeesAlert': '处理薪资前请至少添加一名有钱包的员工。',
  'employer.payrollLoaded': '薪资表已加载',
  'employer.noEmployeesReadyAlert': '处理薪资前请添加员工。',
  'employer.invalidAmount': '请输入正数薪资金额',
  'employer.insufficientFunds': '薪资钱包余额不足。',
  'employer.confirmPayroll': '确认薪资',
  'employer.runPayrollBtn': '处理薪资',
  'employer.payrollComplete': '薪资处理完成',
  'employer.payrollPartial': '薪资部分处理',
  'about.cannotOpenLink': '无法打开链接',
  'about.visitUrl': '请访问该链接',
  'about.development': '开发',
  'about.production': '生产',
  'wallet.serverError': '无法连接到服务器。',
"""

zh_start = content.index("const zh: TranslationMap = {")
ja_start = content.index("const ja: TranslationMap = {")

zh_section = content[zh_start:ja_start]

old_marker_start = "  'common.back': 'Retour',"
old_marker_end = "  'wallet.serverError': 'Impossible de joindre le serveur.',\n"

idx_start = zh_section.index(old_marker_start)
idx_end = zh_section.index(old_marker_end) + len(old_marker_end)

new_zh_section = zh_section[:idx_start] + ZH_BLOCK + zh_section[idx_end:]
new_content = content[:zh_start] + new_zh_section + content[ja_start:]

with open(path, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Done. ZH replaced.")
