import re

path = r"c:\EGWallet\src\i18n\translations.ts"
with open(path, encoding="utf-8") as f:
    content = f.read()

# Marker: the French new-keys block ends just before "const es"
# We'll replace the block between "const es" new-keys comment and "const pt"
# Strategy: find the second occurrence of "'common.back'" and replace up to (not including) "const pt"

ES_BLOCK = """  // -- NUEVAS CLAVES (Español) --
  'common.back': 'Atrás',
  'common.done': 'Listo',
  'common.notAuthenticated': 'No autenticado',
  'common.networkError': 'Error de red. Inténtalo de nuevo.',
  'common.serverUnreachable': 'No se puede conectar al servidor.',
  'common.areYouSure': '¿Estás seguro?',
  'common.justNow': 'Ahora mismo',
  'common.minsAgo': 'min',
  'common.hoursAgo': 'h',
  'common.daysAgo': 'd',
  'auth.enterEmail': 'Por favor, introduce tu correo electrónico',
  'auth.enterPassword': 'Por favor, introduce tu contraseña',
  'auth.passwordTooShort': 'La contraseña debe tener al menos 8 caracteres',
  'auth.accountCreated': '¡Cuenta creada con éxito!',
  'auth.signUpError': 'Error de registro',
  'auth.signInError': 'Error de inicio de sesión',
  'auth.checkCredentials': 'Por favor, verifica tus credenciales e inténtalo de nuevo',
  'auth.emailPlaceholder': 'tu.correo@ejemplo.com',
  'auth.passwordPlaceholder': 'Introduce tu contraseña',
  'auth.passwordHint': 'Mínimo 8 caracteres',
  'auth.termsAgreement': 'Al continuar, aceptas nuestros Términos de servicio y Política de privacidad',
  'send.selectSourceWallet': 'Selecciona la billetera de origen',
  'send.enterValidAmount': 'Introduce un monto válido',
  'send.enterDestWalletId': 'Introduce el ID de la billetera destinataria',
  'send.enterCardNumber': 'Introduce el número de tarjeta',
  'send.enterCardExpiry': 'Introduce la fecha de vencimiento',
  'send.enterCardholderName': 'Introduce el nombre del titular',
  'send.enterBankName': 'Introduce el nombre del banco',
  'send.enterAccountNumber': 'Introduce el número de cuenta',
  'send.enterAccountHolderName': 'Introduce el nombre del titular de la cuenta',
  'send.bankWithdrawal': 'Retiro bancario',
  'send.payNow': 'Pagar ahora',
  'send.transactionFailed': 'Transacción fallida',
  'send.backendUnavailable': 'Servicio no disponible. Inténtalo de nuevo.',
  'send.scamWarningSigns': 'Señales de estafa',
  'send.reviewTransaction': 'Revisar transacción',
  'send.reviewWithdrawal': 'Revisar retiro',
  'send.payingFrom': 'Pagando desde',
  'send.mobileOperator': 'Operador móvil',
  'send.accountLabel': 'Cuenta',
  'send.phoneLabel': 'Teléfono',
  'send.youWithdraw': 'Tú retiras',
  'send.senderCurrency': 'Moneda del remitente',
  'send.yourCurrency': 'Tu moneda',
  'send.youReceive': 'Tú recibes',
  'send.confirmAndSend': 'Confirmar y enviar',
  'send.confirmWithdrawal': 'Confirmar retiro',
  'send.transferSubtitle': 'Transfiere fondos a otra billetera',
  'send.withdrawSubtitle': 'Retirar a tu cuenta bancaria',
  'send.loadingWallets': 'Cargando billeteras...',
  'send.recipientPlaceholder': 'ID de billetera o @usuario',
  'send.intlFeeHint': 'Comisión: 1,75% - cuenta bancaria en el extranjero',
  'send.localFeeHint': 'Comisión: 1,28% - banco local o dinero móvil',
  'send.bankDays': '3 a 5 días',
  'send.paymentSentToast': 'Pago enviado',
  'send.scamWarningText': 'No envíes dinero a personas que no conozcas personalmente.',
  'send.withdrawalFeeInfo': 'Se aplican comisiones de retiro',
  'send.fxFeeInfo': 'Se aplica una comisión de cambio del 1,15%',
  'send.sameCurrencyFree': 'Las transferencias en la misma moneda son gratuitas. Sin comisiones.',
  'settings.couldNotSetUsername': 'No se pudo establecer el nombre de usuario',
  'settings.usernameSetTitle': 'Nombre de usuario establecido',
  'settings.usernameSetMessage': 'Tu identificador ha sido guardado',
  'settings.deleteAccountConfirmFull': '¿Estás seguro de que deseas eliminar tu cuenta?',
  'settings.accountDeletionTitle': 'Eliminación de cuenta',
  'settings.accountDeletionMessage': 'Por favor, contacta con soporte para eliminar tu cuenta.',
  'settings.bugReportSubtitle': 'Describe lo que salió mal.',
  'settings.bugDescribePlaceholder': 'Describe el problema...',
  'settings.bugSend': 'Enviar',
  'settings.describeBugIssue': 'Por favor, describe el problema.',
  'settings.currencyUpdated': 'Moneda actualizada',
  'settings.languageUpdated': 'Idioma actualizado',
  'settings.languageUpdatedMessage': 'El idioma de la aplicación ha sido actualizado',
  'settings.autoConvertOnDesc': 'Convertir automáticamente todos los pagos entrantes',
  'settings.autoConvertOffDesc': 'Recibir pagos en la moneda original.',
  'settings.autoConvertEnabled': 'Conversión automática activada',
  'settings.autoConvertDisabled': 'Conversión automática desactivada',
  'settings.faceLock': 'Bloqueo facial',
  'settings.fingerprintLock': 'Bloqueo por huella',
  'settings.faceLockSubtitle': 'Requiere reconocimiento facial para desbloquear',
  'settings.fingerprintLockSubtitle': 'Requiere huella dactilar para desbloquear',
  'settings.faceIdSubtitle': 'Desbloquear con cara o huella',
  'settings.biometricEnabled': 'Bloqueo biométrico activado',
  'settings.biometricDisabled': 'Bloqueo biométrico desactivado',
  'settings.setUsernameTitle': 'Establecer nombre de usuario',
  'settings.usernameModalSubtitle': 'Otros pueden enviarte dinero usando tu identificador',
  'settings.usernamePlaceholder': 'tunombre',
  'settings.currencyModalDesc': 'Selecciona tu moneda manualmente si no se detectó automáticamente.',
  'settings.searchCurrencyPlaceholder': 'Buscar moneda o país...',
  'settings.currencyHelpText2': '¿No es tu moneda? Pulsa arriba para seleccionar otra.',
  'receipt.addedTo': 'Añadido a',
  'receipt.walletId': 'ID de billetera',
  'receipt.senderCurrency': 'Moneda del remitente',
  'receipt.transferFee': 'Comisión de transferencia',
  'receipt.fxRate': 'Tipo de cambio',
  'receipt.dateTime': 'Fecha y hora',
  'receipt.reference': 'Referencia',
  'receipt.status': 'Estado',
  'receipt.recipientCurrency': 'Moneda del destinatario',
  'qrScan.invalidQrTitle': 'Código QR inválido',
  'qrScan.invalidQrMessage': 'Este código QR no pertenece a EGWallet.',
  'qrScan.unsupportedQrTitle': 'QR no compatible',
  'qrScan.unsupportedQrMessage': 'Este tipo de código QR no es compatible.',
  'qrScan.qrExpiredTitle': 'QR vencido',
  'qrScan.qrExpiredMessage': 'Este QR de pago ha vencido. Solicita uno nuevo.',
  'qrScan.walletLoadError': 'No se pudo cargar tu billetera. Inténtalo de nuevo.',
  'qrScan.missingWalletId': 'Este código QR no contiene una billetera destinataria.',
  'qrScan.invalidQrAmount': 'Este código QR contiene un monto inválido.',
  'qrScan.missingQrCurrency': 'Este código QR no contiene moneda.',
  'qrScan.invalidAmount': 'Introduce un monto válido mayor que 0.',
  'qrScan.missingCurrency': 'Por favor, introduce la moneda.',
  'qrScan.cantPayYourself': 'No puedes pagarte a ti mismo.',
  'qrScan.paymentSentTitle': 'Pago enviado',
  'qrScan.paymentSentMsg': 'Tu pago se envió correctamente.',
  'qrScan.somethingWentWrong': 'Algo salió mal. Inténtalo de nuevo.',
  'qrScan.payViaQr': 'Pagar con QR',
  'qrScan.expired': 'Vencido',
  'qrScan.expiresIn': 'Vence en',
  'qrScan.validFor': 'Válido aprox.',
  'qr.requestTimeout': 'La solicitud tardó demasiado. Inténtalo de nuevo.',
  'qr.contactSupportError': 'Si el problema persiste, contacta con soporte.',
  'kyc.cameraPermission': 'Permiso de cámara',
  'kyc.cameraPermissionMsg': 'Por favor, permite el acceso a la cámara para fotografiar tus documentos.',
  'kyc.galleryPermission': 'Permiso de galería',
  'kyc.galleryPermissionMsg': 'Por favor, permite el acceso a la galería para cargar documentos.',
  'kyc.invalidDocType': 'Tipo de documento inválido',
  'kyc.invalidDocTypeMsg': 'Este tipo de documento no es aceptado.',
  'kyc.invalidFileType': 'Formato de archivo inválido',
  'kyc.invalidFileTypeMsg': 'Solo se aceptan imágenes JPEG, PNG y WEBP.',
  'kyc.invalidImage': 'Imagen inválida',
  'kyc.invalidImageMsg': 'No se pudo leer la imagen seleccionada. Prueba con otra.',
  'kyc.fileTooLarge': 'Archivo demasiado grande',
  'kyc.fileTooLargeMsg': 'Elige una imagen de menos de 10 MB.',
  'kyc.documentSubmittedTitle': 'Documento enviado',
  'kyc.documentSubmittedMsg': 'Nuestro equipo revisará tu documento en 1 o 2 días hábiles.',
  'kyc.documentCaptured': 'Documento capturado',
  'kyc.documentCapturedMsg': 'Foto guardada. Pulsa Cargar para enviar.',
  'kyc.uploadFailed': 'Error al cargar',
  'kyc.takePhoto': 'Tomar foto',
  'kyc.chooseFromGallery': 'Elegir de la galería',
  'kyc.idCardInstructions': 'Coloca tu documento sobre una superficie plana. Asegúrate de que las esquinas sean visibles.',
  'kyc.passportInstructions': 'Abre tu pasaporte en la página de la foto. La foto y el número deben ser legibles.',
  'kyc.driversLicenseInstructions': 'Coloca tu licencia sobre una superficie plana. La foto y el número deben ser legibles.',
  'kyc.proofOfAddressInstructions': 'Carga una factura o carta oficial con fecha de los últimos 3 meses.',
  'kyc.dailyLimitsTitle': 'Límites diarios de transacción',
  'kyc.dailySendingLimit': 'Límite diario de envío (USD)',
  'kyc.dailyLimitDesc': 'Este es el monto máximo que puedes enviar en 24 horas.',
  'kyc.walletCapacityTitle': 'Capacidad de la billetera',
  'kyc.maxBalance': 'Saldo máximo: 250.000 USD',
  'kyc.walletCapacityDesc': 'Tu billetera no puede superar este monto.',
  'kyc.feesTitle': 'Comisiones y cargos',
  'kyc.feesDisclaimer': 'Todas las comisiones se muestran antes de confirmar. Sin cargos ocultos.',
  'kyc.regionalInfoTitle': 'Información regional',
  'kyc.regionGQ': 'Guinea Ecuatorial',
  'kyc.regionAF': 'África',
  'kyc.regionGlobal': 'Global',
  'kyc.regionLabel': 'Región:',
  'kyc.primaryCurrency': 'Moneda principal:',
  'budget.enterValidAmount': 'Por favor, introduce un monto válido',
  'budget.createBudgetTitle': 'Crear presupuesto',
  'budget.createAction': 'Crear',
  'budget.noBudgets': 'Sin presupuestos',
  'budget.noBudgetsDesc': 'Pulsa + para crear un límite mensual de gasto',
  'budget.perMonth': '/mes',
  'budget.currencyLabel': 'Moneda',
  'budget.budgetCreated': 'Presupuesto creado',
  'budget.budgetSaved': 'Presupuesto guardado',
  'card.createVirtualCardTitle': 'Crear tarjeta virtual',
  'card.createVirtualCardMsg': 'Crear una nueva tarjeta virtual para compras en línea',
  'card.createAction': 'Crear',
  'card.freezeConfirmMsg': '¿Bloquear esta tarjeta virtual?',
  'card.unfreezeConfirmMsg': '¿Desbloquear esta tarjeta virtual?',
  'card.cardCreated': 'Tarjeta virtual creada',
  'trusted.removeTitle': 'Eliminar dispositivo',
  'trusted.removeMessage': '¿Estás seguro de que deseas eliminar este dispositivo?',
  'trusted.removedTitle': 'Eliminado',
  'trusted.removedMsg': 'Dispositivo eliminado',
  'trusted.trustedTitle': 'De confianza',
  'trusted.trustedMsg': 'Dispositivo marcado como de confianza',
  'biometric.title': 'EGWallet está bloqueado',
  'biometric.touchFingerprint': 'Toca el sensor de huella para desbloquear',
  'biometric.lookAtDevice': 'Mira tu dispositivo para desbloquear',
  'biometric.authenticate': 'Autentícate para desbloquear',
  'biometric.unlock': 'Desbloquear',
  'biometric.footer': 'Tu billetera está protegida con autenticación biométrica',
  'dispute.selectTxError': 'Por favor, selecciona una transacción para disputar',
  'dispute.describeError': 'Por favor, describe el problema',
  'dispute.minCharsError': 'Proporciona al menos 10 caracteres para describir el problema',
  'dispute.submittedTitle': 'Disputa enviada',
  'dispute.submittedMsg': 'Tu disputa ha sido enviada para revisión.',
  'dispute.sendEmailButton': 'Enviar correo al soporte',
  'dispute.doneButton': 'Listo',
  'dispute.emailFailedTitle': 'Error al abrir el correo',
  'dispute.emailFailedMsg': 'Contáctanos manualmente en support@egwallet.com',
  'dispute.sentToSupport': 'Las disputas se envían a nuestro equipo de soporte.',
  'dispute.txTypeSend': 'Envío',
  'dispute.txTypeReceive': 'Recepción',
  'dispute.txTypeWithdrawal': 'Retiro',
  'dispute.aiSuggestion.unauthorized': 'Revisa tu actividad de inicio de sesión y cambia tu contraseña.',
  'dispute.aiSuggestion.wrongAmount': 'Verifica el tipo de cambio y las comisiones aplicadas.',
  'dispute.aiSuggestion.notReceived': 'Verifica que el ID de billetera sea correcto y revisa todos tus saldos.',
  'dispute.aiSuggestion.duplicate': 'Revisa tu historial de transacciones en busca de montos similares.',
  'dispute.aiSuggestion.other': 'Describe tu problema en detalle incluyendo IDs de transacción y montos.',
  'payRequest.invalidLink': 'Enlace de pago inválido.',
  'payRequest.loadError': 'No se pudo cargar esta solicitud. Verifica tu conexión e inténtalo de nuevo.',
  'payRequest.loginRequired': 'Inicio de sesión requerido',
  'payRequest.loginMsg': 'Inicia sesión para realizar este pago.',
  'payRequest.logIn': 'Iniciar sesión',
  'payRequest.noWallet': 'No se encontró billetera. Inténtalo de nuevo.',
  'payRequest.paymentSentTitle': '¡Pago enviado!',
  'payRequest.paymentSentMsg': 'Pago completado con éxito.',
  'payRequest.paymentFailed': 'Pago fallido',
  'payRequest.couldNotProcess': 'No se pudo procesar el pago.',
  'deposit.missingBankFields': 'Por favor, completa todos los campos bancarios.',
  'deposit.missingCardFields': 'Por favor, completa todos los campos de la tarjeta, incluido el CVC.',
  'deposit.tooSmall': 'Por favor, introduce un monto de depósito válido.',
  'deposit.sessionExpired': 'Tu sesión ha expirado. Por favor, vuelve a iniciar sesión.',
  'deposit.serviceUnavailable': 'No se pudo conectar al servidor. Inténtalo de nuevo.',
  'deposit.depositSubmitted': 'Tu pago está siendo procesado.',
  'deposit.addBankAccount': 'Añadir cuenta bancaria',
  'deposit.addCreditCard': 'Añadir tarjeta de crédito',
  'deposit.addDebitCard': 'Añadir tarjeta de débito',
  'deposit.choosePaymentMethod': 'Elegir método de pago',
  'deposit.selectedSuffix': '(seleccionado)',
  'deposit.stripeAvailable': 'Stripe disponible - pagos con tarjeta real habilitados.',
  'deposit.demoMode': 'Modo demostración - no se cobra dinero real.',
  'request.requestSentToast': 'Solicitud enviada',
  'request.sentTitle': 'Solicitud enviada',
  'request.sentMsg': 'Tu solicitud ha sido enviada con éxito.',
  'request.missingFirstName': 'Por favor, introduce un nombre.',
  'request.missingLastName': 'Por favor, introduce un apellido.',
  'request.invalidEmail': 'Por favor, introduce una dirección de correo válida.',
  'request.employeeAddedTitle': 'Empleado añadido',
  'request.employeeAddedMsg': 'El empleado ha sido añadido a tu equipo.',
  'request.selectEmployee': 'Por favor, selecciona primero un empleado.',
  'request.invalidAmount': 'Por favor, introduce un monto válido.',
  'request.confirmPayrollTitle': 'Confirmar solicitud de nómina',
  'request.sendRequestBtn': 'Enviar solicitud',
  'request.payrollSentMsg': 'Solicitud de pago enviada.',
  'request.cancelRequestTitle': 'Cancelar solicitud',
  'request.noteOptionalLabel': 'Nota (opcional)',
  'request.notePlaceholder': '¿Para qué es esto?',
  'request.statusPending': 'Pendiente',
  'request.statusPaid': 'Pagado',
  'request.statusCancelled': 'Cancelado',
  'report.enterTitle': 'Por favor, introduce un título',
  'report.describeTheProblem': 'Por favor, describe el problema',
  'report.submittedTitle': 'Informe enviado',
  'report.submittedWithTicket': '¡Gracias! Nuestro equipo revisará tu informe en 24 horas.',
  'report.submittedNoTicket': '¡Gracias por tu comentario!',
  'report.submitFailed': 'Error al enviar el informe. Inténtalo de nuevo.',
  'employer.registerRequired': 'El nombre de la empresa y el NIF son obligatorios',
  'employer.registrationSuccess': '¡La empresa está registrada y verificada!',
  'employer.registrationSuccessDemo': '¡La empresa está registrada!',
  'employer.walletFunded': 'Billetera financiada',
  'employer.walletFundedMsg': 'Añadido a tu billetera de financiación.',
  'employer.walletFundedDemo': 'Billetera financiada',
  'employer.employeeEmailRequired': 'El correo electrónico del empleado es obligatorio',
  'employer.employeeAdded': 'El empleado ha sido añadido a tu lista de nómina.',
  'employer.employeeAddedDemo': 'Empleado añadido',
  'employer.noEmployeesAlert': 'Añade al menos un empleado con billetera antes de procesar la nómina.',
  'employer.payrollLoaded': 'Nómina cargada',
  'employer.noEmployeesReadyAlert': 'Añade empleados antes de procesar la nómina.',
  'employer.invalidAmount': 'Introduce un monto de nómina positivo',
  'employer.insufficientFunds': 'Fondos insuficientes en tu billetera de nómina.',
  'employer.confirmPayroll': 'Confirmar nómina',
  'employer.runPayrollBtn': 'Procesar nómina',
  'employer.payrollComplete': 'Nómina completada',
  'employer.payrollPartial': 'Nómina parcial',
  'about.cannotOpenLink': 'No se puede abrir el enlace',
  'about.visitUrl': 'Por favor, visita la URL',
  'about.development': 'Desarrollo',
  'about.production': 'Producción',
  'wallet.serverError': 'No se puede conectar al servidor.',
"""

# Find the Spanish new-keys block: starts after "const es" section's dispute.hint line
# and ends just before "const pt"
# We'll use a regex to find the block between the second occurrence of the French new-keys
# and replace it with Spanish

# Find positions of "const es" and "const pt"
es_start = content.index("const es: TranslationMap = {")
pt_start = content.index("const pt: TranslationMap = {")

es_section = content[es_start:pt_start]

# Find the French fallback new-keys block inside es_section
# It starts with "  'common.back': 'Retour'," and ends with "'wallet.serverError': 'Impossible de joindre le serveur.,"
old_marker_start = "  'common.back': 'Retour',"
old_marker_end = "  'wallet.serverError': 'Impossible de joindre le serveur.',\n"

idx_start = es_section.index(old_marker_start)
idx_end = es_section.index(old_marker_end) + len(old_marker_end)

old_block = es_section[idx_start:idx_end]
new_es_section = es_section[:idx_start] + ES_BLOCK + es_section[idx_end:]

new_content = content[:es_start] + new_es_section + content[pt_start:]

with open(path, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Done. ES replaced.")
