path = r"c:\EGWallet\src\i18n\translations.ts"
with open(path, encoding="utf-8") as f:
    content = f.read()

PT_BLOCK = """  // -- NOVAS CHAVES (Português) --
  'common.back': 'Voltar',
  'common.done': 'Concluído',
  'common.notAuthenticated': 'Não autenticado',
  'common.networkError': 'Erro de rede. Tente novamente.',
  'common.serverUnreachable': 'Não foi possível conectar ao servidor.',
  'common.areYouSure': 'Tem certeza?',
  'common.justNow': 'Agora mesmo',
  'common.minsAgo': 'min',
  'common.hoursAgo': 'h',
  'common.daysAgo': 'd',
  'auth.enterEmail': 'Por favor, insira seu e-mail',
  'auth.enterPassword': 'Por favor, insira sua senha',
  'auth.passwordTooShort': 'A senha deve ter pelo menos 8 caracteres',
  'auth.accountCreated': 'Conta criada com sucesso!',
  'auth.signUpError': 'Erro no cadastro',
  'auth.signInError': 'Erro no início de sessão',
  'auth.checkCredentials': 'Por favor, verifique suas credenciais e tente novamente',
  'auth.emailPlaceholder': 'seu.email@exemplo.com',
  'auth.passwordPlaceholder': 'Insira sua senha',
  'auth.passwordHint': 'Mínimo de 8 caracteres',
  'auth.termsAgreement': 'Ao continuar, você concorda com nossos Termos de Serviço e Política de Privacidade',
  'send.selectSourceWallet': 'Selecione a carteira de origem',
  'send.enterValidAmount': 'Insira um valor válido',
  'send.enterDestWalletId': 'Insira o ID da carteira destinatária',
  'send.enterCardNumber': 'Insira o número do cartão',
  'send.enterCardExpiry': 'Insira a data de validade',
  'send.enterCardholderName': 'Insira o nome do titular',
  'send.enterBankName': 'Insira o nome do banco',
  'send.enterAccountNumber': 'Insira o número da conta',
  'send.enterAccountHolderName': 'Insira o nome do titular da conta',
  'send.bankWithdrawal': 'Saque bancário',
  'send.payNow': 'Pagar agora',
  'send.transactionFailed': 'Transação falhou',
  'send.backendUnavailable': 'Serviço indisponível. Tente novamente.',
  'send.scamWarningSigns': 'Sinais de fraude',
  'send.reviewTransaction': 'Revisar transação',
  'send.reviewWithdrawal': 'Revisar saque',
  'send.payingFrom': 'Pagando de',
  'send.mobileOperator': 'Operadora móvel',
  'send.accountLabel': 'Conta',
  'send.phoneLabel': 'Telefone',
  'send.youWithdraw': 'Você saca',
  'send.senderCurrency': 'Moeda do remetente',
  'send.yourCurrency': 'Sua moeda',
  'send.youReceive': 'Você recebe',
  'send.confirmAndSend': 'Confirmar e enviar',
  'send.confirmWithdrawal': 'Confirmar saque',
  'send.transferSubtitle': 'Transferir fundos para outra carteira',
  'send.withdrawSubtitle': 'Sacar para sua conta bancária',
  'send.loadingWallets': 'Carregando carteiras...',
  'send.recipientPlaceholder': 'ID da carteira ou @usuario',
  'send.intlFeeHint': 'Taxa: 1,75% - conta bancária no exterior',
  'send.localFeeHint': 'Taxa: 1,28% - banco local ou dinheiro móvel',
  'send.bankDays': '3 a 5 dias',
  'send.paymentSentToast': 'Pagamento enviado',
  'send.scamWarningText': 'Não envie dinheiro para pessoas que você não conhece pessoalmente.',
  'send.withdrawalFeeInfo': 'Taxas de saque são aplicadas',
  'send.fxFeeInfo': 'Taxa de câmbio de 1,15% aplicável',
  'send.sameCurrencyFree': 'Transferências na mesma moeda são gratuitas. Sem taxas.',
  'settings.couldNotSetUsername': 'Não foi possível definir o nome de usuário',
  'settings.usernameSetTitle': 'Nome de usuário definido',
  'settings.usernameSetMessage': 'Seu identificador foi salvo',
  'settings.deleteAccountConfirmFull': 'Tem certeza de que deseja excluir sua conta?',
  'settings.accountDeletionTitle': 'Exclusão de conta',
  'settings.accountDeletionMessage': 'Entre em contato com o suporte para excluir sua conta.',
  'settings.bugReportSubtitle': 'Descreva o que deu errado.',
  'settings.bugDescribePlaceholder': 'Descreva o problema...',
  'settings.bugSend': 'Enviar',
  'settings.describeBugIssue': 'Por favor, descreva o problema.',
  'settings.currencyUpdated': 'Moeda atualizada',
  'settings.languageUpdated': 'Idioma atualizado',
  'settings.languageUpdatedMessage': 'O idioma do aplicativo foi atualizado',
  'settings.autoConvertOnDesc': 'Converter automaticamente todos os pagamentos recebidos',
  'settings.autoConvertOffDesc': 'Receber pagamentos na moeda original.',
  'settings.autoConvertEnabled': 'Conversão automática ativada',
  'settings.autoConvertDisabled': 'Conversão automática desativada',
  'settings.faceLock': 'Bloqueio facial',
  'settings.fingerprintLock': 'Bloqueio por impressão digital',
  'settings.faceLockSubtitle': 'Requer reconhecimento facial para desbloquear',
  'settings.fingerprintLockSubtitle': 'Requer impressão digital para desbloquear',
  'settings.faceIdSubtitle': 'Desbloquear com rosto ou impressão digital',
  'settings.biometricEnabled': 'Bloqueio biométrico ativado',
  'settings.biometricDisabled': 'Bloqueio biométrico desativado',
  'settings.setUsernameTitle': 'Definir nome de usuário',
  'settings.usernameModalSubtitle': 'Outros podem enviar dinheiro para você usando seu identificador',
  'settings.usernamePlaceholder': 'seunome',
  'settings.currencyModalDesc': 'Selecione sua moeda manualmente se não foi detectada automaticamente.',
  'settings.searchCurrencyPlaceholder': 'Pesquisar moeda ou país...',
  'settings.currencyHelpText2': 'Não é sua moeda? Toque acima para selecionar outra.',
  'receipt.addedTo': 'Adicionado a',
  'receipt.walletId': 'ID da carteira',
  'receipt.senderCurrency': 'Moeda do remetente',
  'receipt.transferFee': 'Taxa de transferência',
  'receipt.fxRate': 'Taxa de câmbio',
  'receipt.dateTime': 'Data e hora',
  'receipt.reference': 'Referência',
  'receipt.status': 'Status',
  'receipt.recipientCurrency': 'Moeda do destinatário',
  'qrScan.invalidQrTitle': 'Código QR inválido',
  'qrScan.invalidQrMessage': 'Este código QR não pertence ao EGWallet.',
  'qrScan.unsupportedQrTitle': 'QR não suportado',
  'qrScan.unsupportedQrMessage': 'Este tipo de código QR não é suportado.',
  'qrScan.qrExpiredTitle': 'QR expirado',
  'qrScan.qrExpiredMessage': 'Este QR de pagamento expirou. Solicite um novo.',
  'qrScan.walletLoadError': 'Não foi possível carregar sua carteira. Tente novamente.',
  'qrScan.missingWalletId': 'Este código QR não contém uma carteira destinatária.',
  'qrScan.invalidQrAmount': 'Este código QR contém um valor inválido.',
  'qrScan.missingQrCurrency': 'Este código QR não contém moeda.',
  'qrScan.invalidAmount': 'Insira um valor válido maior que 0.',
  'qrScan.missingCurrency': 'Por favor, insira a moeda.',
  'qrScan.cantPayYourself': 'Você não pode pagar para si mesmo.',
  'qrScan.paymentSentTitle': 'Pagamento enviado',
  'qrScan.paymentSentMsg': 'Seu pagamento foi enviado com sucesso.',
  'qrScan.somethingWentWrong': 'Algo deu errado. Tente novamente.',
  'qrScan.payViaQr': 'Pagar via QR',
  'qrScan.expired': 'Expirado',
  'qrScan.expiresIn': 'Expira em',
  'qrScan.validFor': 'Válido por aprox.',
  'qr.requestTimeout': 'A solicitação demorou muito. Tente novamente.',
  'qr.contactSupportError': 'Se o problema persistir, entre em contato com o suporte.',
  'kyc.cameraPermission': 'Permissão de câmera',
  'kyc.cameraPermissionMsg': 'Por favor, permita o acesso à câmera para fotografar seus documentos.',
  'kyc.galleryPermission': 'Permissão de galeria',
  'kyc.galleryPermissionMsg': 'Por favor, permita o acesso à galeria para carregar documentos.',
  'kyc.invalidDocType': 'Tipo de documento inválido',
  'kyc.invalidDocTypeMsg': 'Este tipo de documento não é aceito.',
  'kyc.invalidFileType': 'Formato de arquivo inválido',
  'kyc.invalidFileTypeMsg': 'Somente imagens JPEG, PNG e WEBP são aceitas.',
  'kyc.invalidImage': 'Imagem inválida',
  'kyc.invalidImageMsg': 'Não foi possível ler a imagem selecionada. Tente outra.',
  'kyc.fileTooLarge': 'Arquivo muito grande',
  'kyc.fileTooLargeMsg': 'Escolha uma imagem menor que 10 MB.',
  'kyc.documentSubmittedTitle': 'Documento enviado',
  'kyc.documentSubmittedMsg': 'Nossa equipe revisará seu documento em 1 a 2 dias úteis.',
  'kyc.documentCaptured': 'Documento capturado',
  'kyc.documentCapturedMsg': 'Foto salva. Toque em Carregar para enviar.',
  'kyc.uploadFailed': 'Falha no envio',
  'kyc.takePhoto': 'Tirar foto',
  'kyc.chooseFromGallery': 'Escolher da galeria',
  'kyc.idCardInstructions': 'Coloque seu documento em uma superfície plana. Certifique-se de que os cantos estejam visíveis.',
  'kyc.passportInstructions': 'Abra seu passaporte na página da foto. A foto e o número devem estar legíveis.',
  'kyc.driversLicenseInstructions': 'Coloque sua carteira em uma superfície plana. A foto e o número devem estar legíveis.',
  'kyc.proofOfAddressInstructions': 'Carregue uma conta ou carta oficial com data dos últimos 3 meses.',
  'kyc.dailyLimitsTitle': 'Limites diários de transação',
  'kyc.dailySendingLimit': 'Limite diário de envio (USD)',
  'kyc.dailyLimitDesc': 'Este é o valor máximo que você pode enviar em 24 horas.',
  'kyc.walletCapacityTitle': 'Capacidade da carteira',
  'kyc.maxBalance': 'Saldo máximo: 250.000 USD',
  'kyc.walletCapacityDesc': 'Sua carteira não pode exceder este valor.',
  'kyc.feesTitle': 'Taxas e encargos',
  'kyc.feesDisclaimer': 'Todas as taxas são exibidas antes da confirmação. Sem cobranças ocultas.',
  'kyc.regionalInfoTitle': 'Informações regionais',
  'kyc.regionGQ': 'Guiné Equatorial',
  'kyc.regionAF': 'África',
  'kyc.regionGlobal': 'Global',
  'kyc.regionLabel': 'Região:',
  'kyc.primaryCurrency': 'Moeda principal:',
  'budget.enterValidAmount': 'Por favor, insira um valor válido',
  'budget.createBudgetTitle': 'Criar orçamento',
  'budget.createAction': 'Criar',
  'budget.noBudgets': 'Sem orçamentos',
  'budget.noBudgetsDesc': 'Toque em + para criar um limite mensal de gastos',
  'budget.perMonth': '/mês',
  'budget.currencyLabel': 'Moeda',
  'budget.budgetCreated': 'Orçamento criado',
  'budget.budgetSaved': 'Orçamento salvo',
  'card.createVirtualCardTitle': 'Criar cartão virtual',
  'card.createVirtualCardMsg': 'Criar um novo cartão virtual para compras online',
  'card.createAction': 'Criar',
  'card.freezeConfirmMsg': 'Bloquear este cartão virtual?',
  'card.unfreezeConfirmMsg': 'Desbloquear este cartão virtual?',
  'card.cardCreated': 'Cartão virtual criado',
  'trusted.removeTitle': 'Remover dispositivo',
  'trusted.removeMessage': 'Tem certeza de que deseja remover este dispositivo?',
  'trusted.removedTitle': 'Removido',
  'trusted.removedMsg': 'Dispositivo removido',
  'trusted.trustedTitle': 'Confiável',
  'trusted.trustedMsg': 'Dispositivo marcado como confiável',
  'biometric.title': 'EGWallet está bloqueado',
  'biometric.touchFingerprint': 'Toque no sensor de impressão digital para desbloquear',
  'biometric.lookAtDevice': 'Olhe para o dispositivo para desbloquear',
  'biometric.authenticate': 'Autentique-se para desbloquear',
  'biometric.unlock': 'Desbloquear',
  'biometric.footer': 'Sua carteira está protegida com autenticação biométrica',
  'dispute.selectTxError': 'Por favor, selecione uma transação para contestar',
  'dispute.describeError': 'Por favor, descreva o problema',
  'dispute.minCharsError': 'Forneça pelo menos 10 caracteres para descrever o problema',
  'dispute.submittedTitle': 'Contestação enviada',
  'dispute.submittedMsg': 'Sua contestação foi enviada para análise.',
  'dispute.sendEmailButton': 'Enviar e-mail ao suporte',
  'dispute.doneButton': 'Concluído',
  'dispute.emailFailedTitle': 'Falha ao abrir o e-mail',
  'dispute.emailFailedMsg': 'Entre em contato conosco manualmente em support@egwallet.com',
  'dispute.sentToSupport': 'As contestações são enviadas à nossa equipe de suporte.',
  'dispute.txTypeSend': 'Envio',
  'dispute.txTypeReceive': 'Recebimento',
  'dispute.txTypeWithdrawal': 'Saque',
  'dispute.aiSuggestion.unauthorized': 'Verifique sua atividade de login e altere sua senha.',
  'dispute.aiSuggestion.wrongAmount': 'Verifique a taxa de câmbio e as taxas aplicadas.',
  'dispute.aiSuggestion.notReceived': 'Verifique se o ID da carteira está correto e consulte todos os seus saldos.',
  'dispute.aiSuggestion.duplicate': 'Revise seu histórico de transações em busca de valores semelhantes.',
  'dispute.aiSuggestion.other': 'Descreva seu problema em detalhes incluindo IDs de transação e valores.',
  'payRequest.invalidLink': 'Link de pagamento inválido.',
  'payRequest.loadError': 'Não foi possível carregar esta solicitação. Verifique sua conexão e tente novamente.',
  'payRequest.loginRequired': 'Login necessário',
  'payRequest.loginMsg': 'Faça login para realizar este pagamento.',
  'payRequest.logIn': 'Entrar',
  'payRequest.noWallet': 'Nenhuma carteira encontrada. Tente novamente.',
  'payRequest.paymentSentTitle': 'Pagamento enviado!',
  'payRequest.paymentSentMsg': 'Pagamento concluído com sucesso.',
  'payRequest.paymentFailed': 'Pagamento falhou',
  'payRequest.couldNotProcess': 'Não foi possível processar o pagamento.',
  'deposit.missingBankFields': 'Por favor, preencha todos os campos bancários.',
  'deposit.missingCardFields': 'Por favor, preencha todos os campos do cartão, incluindo o CVC.',
  'deposit.tooSmall': 'Por favor, insira um valor de depósito válido.',
  'deposit.sessionExpired': 'Sua sessão expirou. Por favor, faça login novamente.',
  'deposit.serviceUnavailable': 'Não foi possível conectar ao servidor. Tente novamente.',
  'deposit.depositSubmitted': 'Seu pagamento está sendo processado.',
  'deposit.addBankAccount': 'Adicionar conta bancária',
  'deposit.addCreditCard': 'Adicionar cartão de crédito',
  'deposit.addDebitCard': 'Adicionar cartão de débito',
  'deposit.choosePaymentMethod': 'Escolher método de pagamento',
  'deposit.selectedSuffix': '(selecionado)',
  'deposit.stripeAvailable': 'Stripe disponível - pagamentos reais com cartão habilitados.',
  'deposit.demoMode': 'Modo demonstração - nenhum valor real é cobrado.',
  'request.requestSentToast': 'Solicitação enviada',
  'request.sentTitle': 'Solicitação enviada',
  'request.sentMsg': 'Sua solicitação foi enviada com sucesso.',
  'request.missingFirstName': 'Por favor, insira um nome.',
  'request.missingLastName': 'Por favor, insira um sobrenome.',
  'request.invalidEmail': 'Por favor, insira um endereço de e-mail válido.',
  'request.employeeAddedTitle': 'Funcionário adicionado',
  'request.employeeAddedMsg': 'O funcionário foi adicionado à sua equipe.',
  'request.selectEmployee': 'Por favor, selecione um funcionário primeiro.',
  'request.invalidAmount': 'Por favor, insira um valor válido.',
  'request.confirmPayrollTitle': 'Confirmar solicitação de folha de pagamento',
  'request.sendRequestBtn': 'Enviar solicitação',
  'request.payrollSentMsg': 'Solicitação de pagamento enviada.',
  'request.cancelRequestTitle': 'Cancelar solicitação',
  'request.noteOptionalLabel': 'Nota (opcional)',
  'request.notePlaceholder': 'Para que é isso?',
  'request.statusPending': 'Pendente',
  'request.statusPaid': 'Pago',
  'request.statusCancelled': 'Cancelado',
  'report.enterTitle': 'Por favor, insira um título',
  'report.describeTheProblem': 'Por favor, descreva o problema',
  'report.submittedTitle': 'Relatório enviado',
  'report.submittedWithTicket': 'Obrigado! Nossa equipe analisará dentro de 24 horas.',
  'report.submittedNoTicket': 'Obrigado pelo seu feedback!',
  'report.submitFailed': 'Falha ao enviar o relatório. Tente novamente.',
  'employer.registerRequired': 'O nome da empresa e o CNPJ são obrigatórios',
  'employer.registrationSuccess': 'A empresa está registrada e verificada!',
  'employer.registrationSuccessDemo': 'A empresa está registrada!',
  'employer.walletFunded': 'Carteira financiada',
  'employer.walletFundedMsg': 'Adicionado à sua carteira de financiamento.',
  'employer.walletFundedDemo': 'Carteira financiada',
  'employer.employeeEmailRequired': 'O e-mail do funcionário é obrigatório',
  'employer.employeeAdded': 'O funcionário foi adicionado à sua lista de folha de pagamento.',
  'employer.employeeAddedDemo': 'Funcionário adicionado',
  'employer.noEmployeesAlert': 'Adicione pelo menos um funcionário com carteira antes de processar a folha de pagamento.',
  'employer.payrollLoaded': 'Folha de pagamento carregada',
  'employer.noEmployeesReadyAlert': 'Adicione funcionários antes de processar a folha de pagamento.',
  'employer.invalidAmount': 'Insira um valor positivo para a folha de pagamento',
  'employer.insufficientFunds': 'Saldo insuficiente na sua carteira de folha de pagamento.',
  'employer.confirmPayroll': 'Confirmar folha de pagamento',
  'employer.runPayrollBtn': 'Processar folha de pagamento',
  'employer.payrollComplete': 'Folha de pagamento concluída',
  'employer.payrollPartial': 'Folha de pagamento parcial',
  'about.cannotOpenLink': 'Não foi possível abrir o link',
  'about.visitUrl': 'Por favor, acesse a URL',
  'about.development': 'Desenvolvimento',
  'about.production': 'Produção',
  'wallet.serverError': 'Não foi possível conectar ao servidor.',
"""

pt_start = content.index("const pt: TranslationMap = {")
ar_start = content.index("const ar: TranslationMap = {")

pt_section = content[pt_start:ar_start]

old_marker_start = "  'common.back': 'Retour',"
old_marker_end = "  'wallet.serverError': 'Impossible de joindre le serveur.',\n"

idx_start = pt_section.index(old_marker_start)
idx_end = pt_section.index(old_marker_end) + len(old_marker_end)

new_pt_section = pt_section[:idx_start] + PT_BLOCK + pt_section[idx_end:]
new_content = content[:pt_start] + new_pt_section + content[ar_start:]

with open(path, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Done. PT replaced.")
