path = r"c:\EGWallet\src\i18n\translations.ts"
with open(path, encoding="utf-8") as f:
    content = f.read()

JA_BLOCK = """  // -- 新しいキー (日本語) --
  'common.back': '戻る',
  'common.done': '完了',
  'common.notAuthenticated': '未認証',
  'common.networkError': 'ネットワークエラーです。もう一度お試しください。',
  'common.serverUnreachable': 'サーバーに接続できません。',
  'common.areYouSure': 'よろしいですか？',
  'common.justNow': 'たった今',
  'common.minsAgo': '分前',
  'common.hoursAgo': '時間前',
  'common.daysAgo': '日前',
  'auth.enterEmail': 'メールアドレスを入力してください',
  'auth.enterPassword': 'パスワードを入力してください',
  'auth.passwordTooShort': 'パスワードは8文字以上必要です',
  'auth.accountCreated': 'アカウントが作成されました！',
  'auth.signUpError': '登録エラー',
  'auth.signInError': 'ログインエラー',
  'auth.checkCredentials': '認証情報を確認してもう一度お試しください',
  'auth.emailPlaceholder': 'your@example.com',
  'auth.passwordPlaceholder': 'パスワードを入力',
  'auth.passwordHint': '8文字以上',
  'auth.termsAgreement': '続行することで、利用規約とプライバシーポリシーに同意したことになります',
  'send.selectSourceWallet': '送金元ウォレットを選択',
  'send.enterValidAmount': '有効な金額を入力してください',
  'send.enterDestWalletId': '受取ウォレットIDを入力',
  'send.enterCardNumber': 'カード番号を入力',
  'send.enterCardExpiry': '有効期限を入力',
  'send.enterCardholderName': 'カード名義人を入力',
  'send.enterBankName': '銀行名を入力',
  'send.enterAccountNumber': '口座番号を入力',
  'send.enterAccountHolderName': '口座名義人を入力',
  'send.bankWithdrawal': '銀行出金',
  'send.payNow': '今すぐ支払う',
  'send.transactionFailed': '取引に失敗しました',
  'send.backendUnavailable': 'サービスが利用できません。後でもう一度お試しください。',
  'send.scamWarningSigns': '詐欺の警告サイン',
  'send.reviewTransaction': '取引を確認',
  'send.reviewWithdrawal': '出金を確認',
  'send.payingFrom': '送金元',
  'send.mobileOperator': 'モバイルキャリア',
  'send.accountLabel': '口座',
  'send.phoneLabel': '電話番号',
  'send.youWithdraw': '出金額',
  'send.senderCurrency': '送金者の通貨',
  'send.yourCurrency': 'あなたの通貨',
  'send.youReceive': '受取額',
  'send.confirmAndSend': '確認して送金',
  'send.confirmWithdrawal': '出金を確認',
  'send.transferSubtitle': '別のウォレットへ送金',
  'send.withdrawSubtitle': '銀行口座へ出金',
  'send.loadingWallets': 'ウォレットを読み込み中...',
  'send.recipientPlaceholder': 'ウォレットID または @ユーザー名',
  'send.intlFeeHint': '手数料：1.75% - 海外銀行口座',
  'send.localFeeHint': '手数料：1.28% - 国内銀行またはモバイルマネー',
  'send.bankDays': '3〜5営業日',
  'send.paymentSentToast': '支払いが送信されました',
  'send.scamWarningText': '個人的に知らない相手に送金しないでください。',
  'send.withdrawalFeeInfo': '出金手数料が適用されます',
  'send.fxFeeInfo': '1.15%の為替手数料が適用されます',
  'send.sameCurrencyFree': '同通貨の送金は無料です。手数料なし。',
  'settings.couldNotSetUsername': 'ユーザー名を設定できませんでした',
  'settings.usernameSetTitle': 'ユーザー名設定完了',
  'settings.usernameSetMessage': '識別子が保存されました',
  'settings.deleteAccountConfirmFull': 'アカウントを削除してよろしいですか？',
  'settings.accountDeletionTitle': 'アカウント削除',
  'settings.accountDeletionMessage': 'アカウント削除にはサポートにお問い合わせください。',
  'settings.bugReportSubtitle': '何が問題だったかを説明してください。',
  'settings.bugDescribePlaceholder': '問題を説明してください...',
  'settings.bugSend': '送信',
  'settings.describeBugIssue': '問題を説明してください。',
  'settings.currencyUpdated': '通貨が更新されました',
  'settings.languageUpdated': '言語が更新されました',
  'settings.languageUpdatedMessage': 'アプリの言語が更新されました',
  'settings.autoConvertOnDesc': 'すべての受取を自動的に換算する',
  'settings.autoConvertOffDesc': '元の通貨で受け取る。',
  'settings.autoConvertEnabled': '自動換算が有効化されました',
  'settings.autoConvertDisabled': '自動換算が無効化されました',
  'settings.faceLock': '顔認証ロック',
  'settings.fingerprintLock': '指紋ロック',
  'settings.faceLockSubtitle': '解除に顔認証が必要です',
  'settings.fingerprintLockSubtitle': '解除に指紋が必要です',
  'settings.faceIdSubtitle': '顔または指紋でロック解除',
  'settings.biometricEnabled': '生体認証ロックが有効化されました',
  'settings.biometricDisabled': '生体認証ロックが無効化されました',
  'settings.setUsernameTitle': 'ユーザー名を設定',
  'settings.usernameModalSubtitle': '識別子を使って他のユーザーから送金を受け取れます',
  'settings.usernamePlaceholder': 'あなたの名前',
  'settings.currencyModalDesc': '自動検出されなかった場合は、手動で通貨を選択してください。',
  'settings.searchCurrencyPlaceholder': '通貨または国を検索...',
  'settings.currencyHelpText2': '通貨が違いますか？上をタップして別の通貨を選択してください。',
  'receipt.addedTo': '追加先',
  'receipt.walletId': 'ウォレットID',
  'receipt.senderCurrency': '送金者の通貨',
  'receipt.transferFee': '送金手数料',
  'receipt.fxRate': '為替レート',
  'receipt.dateTime': '日時',
  'receipt.reference': '参照番号',
  'receipt.status': 'ステータス',
  'receipt.recipientCurrency': '受取人の通貨',
  'qrScan.invalidQrTitle': '無効なQRコード',
  'qrScan.invalidQrMessage': 'このQRコードはEGWalletのものではありません。',
  'qrScan.unsupportedQrTitle': '非対応のQR',
  'qrScan.unsupportedQrMessage': 'このタイプのQRコードはサポートされていません。',
  'qrScan.qrExpiredTitle': 'QRの有効期限切れ',
  'qrScan.qrExpiredMessage': 'この支払いQRは期限切れです。新しいものをリクエストしてください。',
  'qrScan.walletLoadError': 'ウォレットを読み込めませんでした。もう一度お試しください。',
  'qrScan.missingWalletId': 'このQRコードには受取ウォレットIDが含まれていません。',
  'qrScan.invalidQrAmount': 'このQRコードには無効な金額が含まれています。',
  'qrScan.missingQrCurrency': 'このQRコードには通貨が含まれていません。',
  'qrScan.invalidAmount': '0より大きい有効な金額を入力してください。',
  'qrScan.missingCurrency': '通貨を入力してください。',
  'qrScan.cantPayYourself': '自分自身には支払えません。',
  'qrScan.paymentSentTitle': '支払いが送信されました',
  'qrScan.paymentSentMsg': '支払いが正常に送信されました。',
  'qrScan.somethingWentWrong': '問題が発生しました。もう一度お試しください。',
  'qrScan.payViaQr': 'QRで支払う',
  'qrScan.expired': '期限切れ',
  'qrScan.expiresIn': '有効期限',
  'qrScan.validFor': '有効期間約',
  'qr.requestTimeout': 'リクエストに時間がかかりすぎました。もう一度お試しください。',
  'qr.contactSupportError': '問題が続く場合はサポートにお問い合わせください。',
  'kyc.cameraPermission': 'カメラの許可',
  'kyc.cameraPermissionMsg': '書類を撮影するためカメラへのアクセスを許可してください。',
  'kyc.galleryPermission': 'ギャラリーの許可',
  'kyc.galleryPermissionMsg': '書類をアップロードするためギャラリーへのアクセスを許可してください。',
  'kyc.invalidDocType': '無効な書類タイプ',
  'kyc.invalidDocTypeMsg': 'この種類の書類は受け付けていません。',
  'kyc.invalidFileType': '無効なファイル形式',
  'kyc.invalidFileTypeMsg': 'JPEG、PNG、WEBP画像のみ受け付けています。',
  'kyc.invalidImage': '無効な画像',
  'kyc.invalidImageMsg': '選択した画像を読み込めませんでした。別の画像をお試しください。',
  'kyc.fileTooLarge': 'ファイルが大きすぎます',
  'kyc.fileTooLargeMsg': '10MB未満の画像を選択してください。',
  'kyc.documentSubmittedTitle': '書類が提出されました',
  'kyc.documentSubmittedMsg': '弊社のチームが1〜2営業日以内に書類を確認します。',
  'kyc.documentCaptured': '書類が撮影されました',
  'kyc.documentCapturedMsg': '写真が保存されました。アップロードをタップして送信してください。',
  'kyc.uploadFailed': 'アップロード失敗',
  'kyc.takePhoto': '写真を撮る',
  'kyc.chooseFromGallery': 'ギャラリーから選択',
  'kyc.idCardInstructions': '書類を平らな場所に置き、四隅が見えるようにしてください。',
  'kyc.passportInstructions': 'パスポートの写真ページを開いてください。写真と番号が読み取れる必要があります。',
  'kyc.driversLicenseInstructions': '免許証を平らな場所に置いてください。写真と番号が読み取れる必要があります。',
  'kyc.proofOfAddressInstructions': '過去3ヶ月以内の請求書または公式書類をアップロードしてください。',
  'kyc.dailyLimitsTitle': '1日の取引限度額',
  'kyc.dailySendingLimit': '1日の送金限度額（USD）',
  'kyc.dailyLimitDesc': '24時間以内に送金できる最大金額です。',
  'kyc.walletCapacityTitle': 'ウォレット容量',
  'kyc.maxBalance': '最大残高：250,000 USD',
  'kyc.walletCapacityDesc': 'ウォレットの残高はこの金額を超えることはできません。',
  'kyc.feesTitle': '手数料',
  'kyc.feesDisclaimer': 'すべての手数料は確認前に表示されます。隠れた費用はありません。',
  'kyc.regionalInfoTitle': '地域情報',
  'kyc.regionGQ': '赤道ギニア',
  'kyc.regionAF': 'アフリカ',
  'kyc.regionGlobal': 'グローバル',
  'kyc.regionLabel': '地域：',
  'kyc.primaryCurrency': '主要通貨：',
  'budget.enterValidAmount': '有効な金額を入力してください',
  'budget.createBudgetTitle': '予算を作成',
  'budget.createAction': '作成',
  'budget.noBudgets': '予算なし',
  'budget.noBudgetsDesc': '＋をタップして月次支出の上限を作成',
  'budget.perMonth': '/月',
  'budget.currencyLabel': '通貨',
  'budget.budgetCreated': '予算が作成されました',
  'budget.budgetSaved': '予算が保存されました',
  'card.createVirtualCardTitle': 'バーチャルカードを作成',
  'card.createVirtualCardMsg': 'オンライン購入用の新しいバーチャルカードを作成',
  'card.createAction': '作成',
  'card.freezeConfirmMsg': 'このバーチャルカードを凍結しますか？',
  'card.unfreezeConfirmMsg': 'このバーチャルカードの凍結を解除しますか？',
  'card.cardCreated': 'バーチャルカードが作成されました',
  'trusted.removeTitle': 'デバイスを削除',
  'trusted.removeMessage': 'このデバイスを削除してよろしいですか？',
  'trusted.removedTitle': '削除されました',
  'trusted.removedMsg': 'デバイスが削除されました',
  'trusted.trustedTitle': '信頼済み',
  'trusted.trustedMsg': 'デバイスが信頼済みとしてマークされました',
  'biometric.title': 'EGWalletはロックされています',
  'biometric.touchFingerprint': '指紋センサーに触れてロック解除',
  'biometric.lookAtDevice': 'デバイスを見てロック解除',
  'biometric.authenticate': 'ロック解除のために認証してください',
  'biometric.unlock': 'ロック解除',
  'biometric.footer': 'ウォレットは生体認証で保護されています',
  'dispute.selectTxError': '異議申し立てする取引を選択してください',
  'dispute.describeError': '問題を説明してください',
  'dispute.minCharsError': '問題の説明に少なくとも10文字入力してください',
  'dispute.submittedTitle': '異議申し立てが提出されました',
  'dispute.submittedMsg': '異議申し立てが審査のために送信されました。',
  'dispute.sendEmailButton': 'サポートにメールを送信',
  'dispute.doneButton': '完了',
  'dispute.emailFailedTitle': 'メールを開けませんでした',
  'dispute.emailFailedMsg': 'support@egwallet.comまでお問い合わせください',
  'dispute.sentToSupport': '異議申し立てはサポートチームに送信されます。',
  'dispute.txTypeSend': '送金',
  'dispute.txTypeReceive': '受取',
  'dispute.txTypeWithdrawal': '出金',
  'dispute.aiSuggestion.unauthorized': 'ログイン履歴を確認してパスワードを変更してください。',
  'dispute.aiSuggestion.wrongAmount': '適用された為替レートと手数料を確認してください。',
  'dispute.aiSuggestion.notReceived': 'ウォレットIDが正しいか確認し、すべての残高を確認してください。',
  'dispute.aiSuggestion.duplicate': '類似金額の取引履歴を確認してください。',
  'dispute.aiSuggestion.other': '取引IDと金額を含めて詳細に問題を説明してください。',
  'payRequest.invalidLink': '無効な支払いリンクです。',
  'payRequest.loadError': 'このリクエストを読み込めませんでした。接続を確認して再試行してください。',
  'payRequest.loginRequired': 'ログインが必要です',
  'payRequest.loginMsg': 'この支払いを行うためにログインしてください。',
  'payRequest.logIn': 'ログイン',
  'payRequest.noWallet': 'ウォレットが見つかりませんでした。もう一度お試しください。',
  'payRequest.paymentSentTitle': '支払いが送信されました！',
  'payRequest.paymentSentMsg': '支払いが正常に完了しました。',
  'payRequest.paymentFailed': '支払いに失敗しました',
  'payRequest.couldNotProcess': '支払いを処理できませんでした。',
  'deposit.missingBankFields': 'すべての銀行情報を入力してください。',
  'deposit.missingCardFields': 'CVCを含むすべてのカード情報を入力してください。',
  'deposit.tooSmall': '有効な入金額を入力してください。',
  'deposit.sessionExpired': 'セッションが期限切れです。再度ログインしてください。',
  'deposit.serviceUnavailable': 'サーバーに接続できませんでした。もう一度お試しください。',
  'deposit.depositSubmitted': '支払いを処理中です。',
  'deposit.addBankAccount': '銀行口座を追加',
  'deposit.addCreditCard': 'クレジットカードを追加',
  'deposit.addDebitCard': 'デビットカードを追加',
  'deposit.choosePaymentMethod': '支払い方法を選択',
  'deposit.selectedSuffix': '（選択済み）',
  'deposit.stripeAvailable': 'Stripe利用可能 - 実際のカード支払いが有効です。',
  'deposit.demoMode': 'デモモード - 実際の料金は発生しません。',
  'request.requestSentToast': 'リクエストが送信されました',
  'request.sentTitle': 'リクエストが送信されました',
  'request.sentMsg': 'リクエストが正常に送信されました。',
  'request.missingFirstName': '名前を入力してください。',
  'request.missingLastName': '苗字を入力してください。',
  'request.invalidEmail': '有効なメールアドレスを入力してください。',
  'request.employeeAddedTitle': '従業員が追加されました',
  'request.employeeAddedMsg': '従業員がチームに追加されました。',
  'request.selectEmployee': '最初に従業員を選択してください。',
  'request.invalidAmount': '有効な金額を入力してください。',
  'request.confirmPayrollTitle': '給与リクエストを確認',
  'request.sendRequestBtn': 'リクエストを送信',
  'request.payrollSentMsg': '支払いリクエストが送信されました。',
  'request.cancelRequestTitle': 'リクエストをキャンセル',
  'request.noteOptionalLabel': 'メモ（任意）',
  'request.notePlaceholder': 'これは何のためですか？',
  'request.statusPending': '保留中',
  'request.statusPaid': '支払済み',
  'request.statusCancelled': 'キャンセル済み',
  'report.enterTitle': 'タイトルを入力してください',
  'report.describeTheProblem': '問題を説明してください',
  'report.submittedTitle': 'レポートが提出されました',
  'report.submittedWithTicket': 'ありがとうございます！チームが24時間以内にレポートを確認します。',
  'report.submittedNoTicket': 'フィードバックありがとうございます！',
  'report.submitFailed': 'レポートの送信に失敗しました。もう一度お試しください。',
  'employer.registerRequired': '会社名と税番号は必須です',
  'employer.registrationSuccess': '会社が登録・確認されました！',
  'employer.registrationSuccessDemo': '会社が登録されました！',
  'employer.walletFunded': 'ウォレットに資金が追加されました',
  'employer.walletFundedMsg': '資金ウォレットに追加されました。',
  'employer.walletFundedDemo': 'ウォレットに資金が追加されました',
  'employer.employeeEmailRequired': '従業員のメールアドレスは必須です',
  'employer.employeeAdded': '従業員が給与リストに追加されました。',
  'employer.employeeAddedDemo': '従業員が追加されました',
  'employer.noEmployeesAlert': '給与処理前に、ウォレットを持つ従業員を少なくとも1人追加してください。',
  'employer.payrollLoaded': '給与リストが読み込まれました',
  'employer.noEmployeesReadyAlert': '給与処理前に従業員を追加してください。',
  'employer.invalidAmount': '正の給与金額を入力してください',
  'employer.insufficientFunds': '給与ウォレットの残高が不足しています。',
  'employer.confirmPayroll': '給与を確認',
  'employer.runPayrollBtn': '給与を処理',
  'employer.payrollComplete': '給与処理が完了しました',
  'employer.payrollPartial': '給与の部分処理',
  'about.cannotOpenLink': 'リンクを開けませんでした',
  'about.visitUrl': 'URLにアクセスしてください',
  'about.development': '開発',
  'about.production': '本番',
  'wallet.serverError': 'サーバーに接続できません。',
"""

ja_start = content.index("const ja: TranslationMap = {")
# End boundary: export const translations
end_boundary = "export const translations"
end_start = content.index(end_boundary)

ja_section = content[ja_start:end_start]

old_marker_start = "  'common.back': 'Retour',"
old_marker_end = "  'wallet.serverError': 'Impossible de joindre le serveur.',\n"

idx_start = ja_section.index(old_marker_start)
idx_end = ja_section.index(old_marker_end) + len(old_marker_end)

new_ja_section = ja_section[:idx_start] + JA_BLOCK + ja_section[idx_end:]
new_content = content[:ja_start] + new_ja_section + content[end_start:]

with open(path, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Done. JA replaced.")
