path = r"c:\EGWallet\src\i18n\translations.ts"
with open(path, encoding="utf-8") as f:
    content = f.read()

AR_BLOCK = """  // -- مفاتيح جديدة (العربية) --
  'common.back': 'رجوع',
  'common.done': 'تم',
  'common.notAuthenticated': 'غير مصادق عليه',
  'common.networkError': 'خطأ في الشبكة. يرجى المحاولة مجدداً.',
  'common.serverUnreachable': 'تعذّر الاتصال بالخادم.',
  'common.areYouSure': 'هل أنت متأكد؟',
  'common.justNow': 'الآن',
  'common.minsAgo': 'د',
  'common.hoursAgo': 'س',
  'common.daysAgo': 'ي',
  'auth.enterEmail': 'يرجى إدخال بريدك الإلكتروني',
  'auth.enterPassword': 'يرجى إدخال كلمة المرور',
  'auth.passwordTooShort': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
  'auth.accountCreated': 'تم إنشاء الحساب بنجاح!',
  'auth.signUpError': 'خطأ في التسجيل',
  'auth.signInError': 'خطأ في تسجيل الدخول',
  'auth.checkCredentials': 'يرجى التحقق من بيانات اعتمادك والمحاولة مجدداً',
  'auth.emailPlaceholder': 'بريدك@مثال.com',
  'auth.passwordPlaceholder': 'أدخل كلمة المرور',
  'auth.passwordHint': '8 أحرف على الأقل',
  'auth.termsAgreement': 'بالمتابعة، فإنك توافق على شروط الخدمة وسياسة الخصوصية',
  'send.selectSourceWallet': 'اختر محفظة المصدر',
  'send.enterValidAmount': 'يرجى إدخال مبلغ صحيح',
  'send.enterDestWalletId': 'أدخل معرّف المحفظة المستلمة',
  'send.enterCardNumber': 'أدخل رقم البطاقة',
  'send.enterCardExpiry': 'أدخل تاريخ انتهاء الصلاحية',
  'send.enterCardholderName': 'أدخل اسم حامل البطاقة',
  'send.enterBankName': 'أدخل اسم البنك',
  'send.enterAccountNumber': 'أدخل رقم الحساب',
  'send.enterAccountHolderName': 'أدخل اسم صاحب الحساب',
  'send.bankWithdrawal': 'سحب بنكي',
  'send.payNow': 'ادفع الآن',
  'send.transactionFailed': 'فشلت المعاملة',
  'send.backendUnavailable': 'الخدمة غير متاحة. يرجى المحاولة مجدداً.',
  'send.scamWarningSigns': 'علامات الاحتيال',
  'send.reviewTransaction': 'مراجعة المعاملة',
  'send.reviewWithdrawal': 'مراجعة السحب',
  'send.payingFrom': 'الدفع من',
  'send.mobileOperator': 'شركة الاتصالات',
  'send.accountLabel': 'الحساب',
  'send.phoneLabel': 'الهاتف',
  'send.youWithdraw': 'تسحب',
  'send.senderCurrency': 'عملة المرسل',
  'send.yourCurrency': 'عملتك',
  'send.youReceive': 'تستلم',
  'send.confirmAndSend': 'تأكيد وإرسال',
  'send.confirmWithdrawal': 'تأكيد السحب',
  'send.transferSubtitle': 'تحويل الأموال إلى محفظة أخرى',
  'send.withdrawSubtitle': 'سحب إلى حسابك البنكي',
  'send.loadingWallets': 'جارٍ تحميل المحافظ...',
  'send.recipientPlaceholder': 'معرّف المحفظة أو @المستخدم',
  'send.intlFeeHint': 'رسوم: 1.75% - حساب بنكي خارجي',
  'send.localFeeHint': 'رسوم: 1.28% - بنك محلي أو نقود متنقلة',
  'send.bankDays': '3 إلى 5 أيام',
  'send.paymentSentToast': 'تم إرسال الدفعة',
  'send.scamWarningText': 'لا ترسل أموالاً إلى أشخاص لا تعرفهم شخصياً.',
  'send.withdrawalFeeInfo': 'تطبّق رسوم السحب',
  'send.fxFeeInfo': 'تطبّق رسوم صرف العملات 1.15%',
  'send.sameCurrencyFree': 'التحويلات بنفس العملة مجانية. بدون رسوم.',
  'settings.couldNotSetUsername': 'تعذّر تعيين اسم المستخدم',
  'settings.usernameSetTitle': 'تم تعيين اسم المستخدم',
  'settings.usernameSetMessage': 'تم حفظ معرّفك',
  'settings.deleteAccountConfirmFull': 'هل أنت متأكد من حذف حسابك؟',
  'settings.accountDeletionTitle': 'حذف الحساب',
  'settings.accountDeletionMessage': 'يرجى التواصل مع الدعم لحذف حسابك.',
  'settings.bugReportSubtitle': 'صف ما حدث من خطأ.',
  'settings.bugDescribePlaceholder': 'صف المشكلة...',
  'settings.bugSend': 'إرسال',
  'settings.describeBugIssue': 'يرجى وصف المشكلة.',
  'settings.currencyUpdated': 'تم تحديث العملة',
  'settings.languageUpdated': 'تم تحديث اللغة',
  'settings.languageUpdatedMessage': 'تم تحديث لغة التطبيق',
  'settings.autoConvertOnDesc': 'تحويل جميع المدفوعات الواردة تلقائياً',
  'settings.autoConvertOffDesc': 'استلام المدفوعات بالعملة الأصلية.',
  'settings.autoConvertEnabled': 'التحويل التلقائي مفعّل',
  'settings.autoConvertDisabled': 'التحويل التلقائي معطّل',
  'settings.faceLock': 'قفل الوجه',
  'settings.fingerprintLock': 'قفل بصمة الإصبع',
  'settings.faceLockSubtitle': 'يتطلب التعرف على الوجه لإلغاء القفل',
  'settings.fingerprintLockSubtitle': 'يتطلب بصمة الإصبع لإلغاء القفل',
  'settings.faceIdSubtitle': 'إلغاء القفل بالوجه أو بصمة الإصبع',
  'settings.biometricEnabled': 'القفل البيومتري مفعّل',
  'settings.biometricDisabled': 'القفل البيومتري معطّل',
  'settings.setUsernameTitle': 'تعيين اسم مستخدم',
  'settings.usernameModalSubtitle': 'يمكن للآخرين إرسال أموال إليك باستخدام معرّفك',
  'settings.usernamePlaceholder': 'اسمك',
  'settings.currencyModalDesc': 'اختر عملتك يدوياً إذا لم يتم اكتشافها تلقائياً.',
  'settings.searchCurrencyPlaceholder': 'ابحث عن عملة أو دولة...',
  'settings.currencyHelpText2': 'هل العملة غير صحيحة؟ انقر أعلاه لتحديد أخرى.',
  'receipt.addedTo': 'أضيف إلى',
  'receipt.walletId': 'معرّف المحفظة',
  'receipt.senderCurrency': 'عملة المرسل',
  'receipt.transferFee': 'رسوم التحويل',
  'receipt.fxRate': 'سعر الصرف',
  'receipt.dateTime': 'التاريخ والوقت',
  'receipt.reference': 'المرجع',
  'receipt.status': 'الحالة',
  'receipt.recipientCurrency': 'عملة المستلم',
  'qrScan.invalidQrTitle': 'رمز QR غير صالح',
  'qrScan.invalidQrMessage': 'هذا الرمز لا ينتمي إلى EGWallet.',
  'qrScan.unsupportedQrTitle': 'QR غير مدعوم',
  'qrScan.unsupportedQrMessage': 'هذا النوع من رموز QR غير مدعوم.',
  'qrScan.qrExpiredTitle': 'انتهت صلاحية QR',
  'qrScan.qrExpiredMessage': 'انتهت صلاحية هذا الرمز. اطلب رمزاً جديداً.',
  'qrScan.walletLoadError': 'تعذّر تحميل محفظتك. يرجى المحاولة مجدداً.',
  'qrScan.missingWalletId': 'لا يحتوي هذا الرمز على معرّف محفظة مستلم.',
  'qrScan.invalidQrAmount': 'يحتوي هذا الرمز على مبلغ غير صالح.',
  'qrScan.missingQrCurrency': 'لا يحتوي هذا الرمز على عملة.',
  'qrScan.invalidAmount': 'أدخل مبلغاً صحيحاً أكبر من 0.',
  'qrScan.missingCurrency': 'يرجى إدخال العملة.',
  'qrScan.cantPayYourself': 'لا يمكنك الدفع لنفسك.',
  'qrScan.paymentSentTitle': 'تم إرسال الدفعة',
  'qrScan.paymentSentMsg': 'تم إرسال دفعتك بنجاح.',
  'qrScan.somethingWentWrong': 'حدث خطأ ما. يرجى المحاولة مجدداً.',
  'qrScan.payViaQr': 'الدفع عبر QR',
  'qrScan.expired': 'منتهية الصلاحية',
  'qrScan.expiresIn': 'تنتهي خلال',
  'qrScan.validFor': 'صالحة لمدة تقريبية',
  'qr.requestTimeout': 'استغرق الطلب وقتاً طويلاً. يرجى المحاولة مجدداً.',
  'qr.contactSupportError': 'إذا استمرت المشكلة، تواصل مع الدعم.',
  'kyc.cameraPermission': 'إذن الكاميرا',
  'kyc.cameraPermissionMsg': 'يرجى السماح بالوصول إلى الكاميرا لتصوير مستنداتك.',
  'kyc.galleryPermission': 'إذن المعرض',
  'kyc.galleryPermissionMsg': 'يرجى السماح بالوصول إلى المعرض لرفع المستندات.',
  'kyc.invalidDocType': 'نوع مستند غير صالح',
  'kyc.invalidDocTypeMsg': 'هذا النوع من المستندات غير مقبول.',
  'kyc.invalidFileType': 'تنسيق ملف غير صالح',
  'kyc.invalidFileTypeMsg': 'يُقبل فقط JPEG وPNG وWEBP.',
  'kyc.invalidImage': 'صورة غير صالحة',
  'kyc.invalidImageMsg': 'تعذّر قراءة الصورة المحددة. جرّب صورة أخرى.',
  'kyc.fileTooLarge': 'الملف كبير جداً',
  'kyc.fileTooLargeMsg': 'اختر صورة أصغر من 10 ميجابايت.',
  'kyc.documentSubmittedTitle': 'تم إرسال المستند',
  'kyc.documentSubmittedMsg': 'سيراجع فريقنا مستندك خلال يوم إلى يومين عمل.',
  'kyc.documentCaptured': 'تم التقاط المستند',
  'kyc.documentCapturedMsg': 'تم حفظ الصورة. انقر رفع للإرسال.',
  'kyc.uploadFailed': 'فشل الرفع',
  'kyc.takePhoto': 'التقاط صورة',
  'kyc.chooseFromGallery': 'الاختيار من المعرض',
  'kyc.idCardInstructions': 'ضع مستندك على سطح مستوٍ. تأكد من ظهور الزوايا.',
  'kyc.passportInstructions': 'افتح جواز سفرك على صفحة الصورة. يجب أن تكون الصورة والرقم واضحَين.',
  'kyc.driversLicenseInstructions': 'ضع رخصتك على سطح مستوٍ. يجب أن تكون الصورة والرقم واضحَين.',
  'kyc.proofOfAddressInstructions': 'ارفع فاتورة أو خطاباً رسمياً بتاريخ الأشهر الثلاثة الماضية.',
  'kyc.dailyLimitsTitle': 'الحدود اليومية للمعاملات',
  'kyc.dailySendingLimit': 'حد الإرسال اليومي (USD)',
  'kyc.dailyLimitDesc': 'هذا هو الحد الأقصى للمبلغ الذي يمكنك إرساله في 24 ساعة.',
  'kyc.walletCapacityTitle': 'سعة المحفظة',
  'kyc.maxBalance': 'الرصيد الأقصى: 250,000 USD',
  'kyc.walletCapacityDesc': 'لا يمكن أن يتجاوز رصيد محفظتك هذا المبلغ.',
  'kyc.feesTitle': 'الرسوم والمصاريف',
  'kyc.feesDisclaimer': 'تُعرض جميع الرسوم قبل التأكيد. لا رسوم خفية.',
  'kyc.regionalInfoTitle': 'معلومات إقليمية',
  'kyc.regionGQ': 'غينيا الاستوائية',
  'kyc.regionAF': 'أفريقيا',
  'kyc.regionGlobal': 'عالمي',
  'kyc.regionLabel': 'المنطقة:',
  'kyc.primaryCurrency': 'العملة الأساسية:',
  'budget.enterValidAmount': 'يرجى إدخال مبلغ صحيح',
  'budget.createBudgetTitle': 'إنشاء ميزانية',
  'budget.createAction': 'إنشاء',
  'budget.noBudgets': 'لا توجد ميزانيات',
  'budget.noBudgetsDesc': 'انقر + لإنشاء حد إنفاق شهري',
  'budget.perMonth': '/شهر',
  'budget.currencyLabel': 'العملة',
  'budget.budgetCreated': 'تم إنشاء الميزانية',
  'budget.budgetSaved': 'تم حفظ الميزانية',
  'card.createVirtualCardTitle': 'إنشاء بطاقة افتراضية',
  'card.createVirtualCardMsg': 'إنشاء بطاقة افتراضية جديدة للمشتريات عبر الإنترنت',
  'card.createAction': 'إنشاء',
  'card.freezeConfirmMsg': 'تجميد هذه البطاقة الافتراضية؟',
  'card.unfreezeConfirmMsg': 'إلغاء تجميد هذه البطاقة الافتراضية؟',
  'card.cardCreated': 'تم إنشاء البطاقة الافتراضية',
  'trusted.removeTitle': 'إزالة الجهاز',
  'trusted.removeMessage': 'هل أنت متأكد من إزالة هذا الجهاز؟',
  'trusted.removedTitle': 'تمت الإزالة',
  'trusted.removedMsg': 'تمت إزالة الجهاز',
  'trusted.trustedTitle': 'موثوق',
  'trusted.trustedMsg': 'تم تمييز الجهاز كموثوق',
  'biometric.title': 'EGWallet مقفل',
  'biometric.touchFingerprint': 'المس مستشعر البصمة لإلغاء القفل',
  'biometric.lookAtDevice': 'انظر إلى جهازك لإلغاء القفل',
  'biometric.authenticate': 'المصادقة لإلغاء القفل',
  'biometric.unlock': 'إلغاء القفل',
  'biometric.footer': 'محفظتك محمية بالمصادقة البيومترية',
  'dispute.selectTxError': 'يرجى اختيار معاملة للطعن فيها',
  'dispute.describeError': 'يرجى وصف المشكلة',
  'dispute.minCharsError': 'أدخل 10 أحرف على الأقل لوصف المشكلة',
  'dispute.submittedTitle': 'تم إرسال الطعن',
  'dispute.submittedMsg': 'تم إرسال طعنك للمراجعة.',
  'dispute.sendEmailButton': 'إرسال بريد إلكتروني للدعم',
  'dispute.doneButton': 'تم',
  'dispute.emailFailedTitle': 'فشل فتح البريد',
  'dispute.emailFailedMsg': 'تواصل معنا يدوياً على support@egwallet.com',
  'dispute.sentToSupport': 'تُرسل الطعون إلى فريق الدعم.',
  'dispute.txTypeSend': 'إرسال',
  'dispute.txTypeReceive': 'استلام',
  'dispute.txTypeWithdrawal': 'سحب',
  'dispute.aiSuggestion.unauthorized': 'راجع نشاط تسجيل الدخول وغيّر كلمة مرورك.',
  'dispute.aiSuggestion.wrongAmount': 'تحقق من سعر الصرف والرسوم المطبّقة.',
  'dispute.aiSuggestion.notReceived': 'تأكد من صحة معرّف المحفظة وراجع جميع أرصدتك.',
  'dispute.aiSuggestion.duplicate': 'راجع سجل معاملاتك بحثاً عن مبالغ مماثلة.',
  'dispute.aiSuggestion.other': 'صف مشكلتك بالتفصيل مع معرّفات المعاملات والمبالغ.',
  'payRequest.invalidLink': 'رابط دفع غير صالح.',
  'payRequest.loadError': 'تعذّر تحميل هذا الطلب. تحقق من اتصالك وحاول مجدداً.',
  'payRequest.loginRequired': 'تسجيل الدخول مطلوب',
  'payRequest.loginMsg': 'سجّل الدخول لإتمام هذا الدفع.',
  'payRequest.logIn': 'تسجيل الدخول',
  'payRequest.noWallet': 'لم يتم العثور على محفظة. يرجى المحاولة مجدداً.',
  'payRequest.paymentSentTitle': 'تم إرسال الدفعة!',
  'payRequest.paymentSentMsg': 'اكتملت الدفعة بنجاح.',
  'payRequest.paymentFailed': 'فشل الدفع',
  'payRequest.couldNotProcess': 'تعذّر معالجة الدفعة.',
  'deposit.missingBankFields': 'يرجى ملء جميع الحقول البنكية.',
  'deposit.missingCardFields': 'يرجى ملء جميع حقول البطاقة بما فيها رمز CVC.',
  'deposit.tooSmall': 'يرجى إدخال مبلغ إيداع صحيح.',
  'deposit.sessionExpired': 'انتهت جلستك. يرجى تسجيل الدخول مجدداً.',
  'deposit.serviceUnavailable': 'تعذّر الاتصال بالخادم. يرجى المحاولة مجدداً.',
  'deposit.depositSubmitted': 'دفعتك قيد المعالجة.',
  'deposit.addBankAccount': 'إضافة حساب بنكي',
  'deposit.addCreditCard': 'إضافة بطاقة ائتمان',
  'deposit.addDebitCard': 'إضافة بطاقة خصم',
  'deposit.choosePaymentMethod': 'اختيار طريقة الدفع',
  'deposit.selectedSuffix': '(محدد)',
  'deposit.stripeAvailable': 'Stripe متاح - مدفوعات البطاقة الحقيقية مفعّلة.',
  'deposit.demoMode': 'وضع العرض التوضيحي - لا يتم خصم أموال حقيقية.',
  'request.requestSentToast': 'تم إرسال الطلب',
  'request.sentTitle': 'تم إرسال الطلب',
  'request.sentMsg': 'تم إرسال طلبك بنجاح.',
  'request.missingFirstName': 'يرجى إدخال الاسم الأول.',
  'request.missingLastName': 'يرجى إدخال اسم العائلة.',
  'request.invalidEmail': 'يرجى إدخال عنوان بريد إلكتروني صحيح.',
  'request.employeeAddedTitle': 'تمت إضافة الموظف',
  'request.employeeAddedMsg': 'تمت إضافة الموظف إلى فريقك.',
  'request.selectEmployee': 'يرجى اختيار موظف أولاً.',
  'request.invalidAmount': 'يرجى إدخال مبلغ صحيح.',
  'request.confirmPayrollTitle': 'تأكيد طلب الرواتب',
  'request.sendRequestBtn': 'إرسال الطلب',
  'request.payrollSentMsg': 'تم إرسال طلب الدفع.',
  'request.cancelRequestTitle': 'إلغاء الطلب',
  'request.noteOptionalLabel': 'ملاحظة (اختياري)',
  'request.notePlaceholder': 'لماذا هذا؟',
  'request.statusPending': 'قيد الانتظار',
  'request.statusPaid': 'مدفوع',
  'request.statusCancelled': 'ملغى',
  'report.enterTitle': 'يرجى إدخال عنوان',
  'report.describeTheProblem': 'يرجى وصف المشكلة',
  'report.submittedTitle': 'تم إرسال التقرير',
  'report.submittedWithTicket': 'شكراً! سيراجع فريقنا تقريرك خلال 24 ساعة.',
  'report.submittedNoTicket': 'شكراً على ملاحظاتك!',
  'report.submitFailed': 'فشل إرسال التقرير. يرجى المحاولة مجدداً.',
  'employer.registerRequired': 'اسم الشركة والرقم الضريبي إلزاميان',
  'employer.registrationSuccess': 'تم تسجيل الشركة والتحقق منها!',
  'employer.registrationSuccessDemo': 'تم تسجيل الشركة!',
  'employer.walletFunded': 'تم تمويل المحفظة',
  'employer.walletFundedMsg': 'أضيف إلى محفظة التمويل.',
  'employer.walletFundedDemo': 'تم تمويل المحفظة',
  'employer.employeeEmailRequired': 'البريد الإلكتروني للموظف إلزامي',
  'employer.employeeAdded': 'تمت إضافة الموظف إلى قائمة الرواتب.',
  'employer.employeeAddedDemo': 'تمت إضافة الموظف',
  'employer.noEmployeesAlert': 'أضف موظفاً واحداً على الأقل قبل معالجة الرواتب.',
  'employer.payrollLoaded': 'تم تحميل كشف الرواتب',
  'employer.noEmployeesReadyAlert': 'أضف موظفين قبل معالجة الرواتب.',
  'employer.invalidAmount': 'أدخل مبلغاً إيجابياً للرواتب',
  'employer.insufficientFunds': 'رصيد غير كافٍ في محفظة الرواتب.',
  'employer.confirmPayroll': 'تأكيد كشف الرواتب',
  'employer.runPayrollBtn': 'معالجة الرواتب',
  'employer.payrollComplete': 'اكتمل كشف الرواتب',
  'employer.payrollPartial': 'كشف رواتب جزئي',
  'about.cannotOpenLink': 'تعذّر فتح الرابط',
  'about.visitUrl': 'يرجى زيارة الرابط',
  'about.development': 'التطوير',
  'about.production': 'الإنتاج',
  'wallet.serverError': 'تعذّر الاتصال بالخادم.',
"""

ar_start = content.index("const ar: TranslationMap = {")
zh_start = content.index("const zh: TranslationMap = {")

ar_section = content[ar_start:zh_start]

old_marker_start = "  'common.back': 'Retour',"
old_marker_end = "  'wallet.serverError': 'Impossible de joindre le serveur.',\n"

idx_start = ar_section.index(old_marker_start)
idx_end = ar_section.index(old_marker_end) + len(old_marker_end)

new_ar_section = ar_section[:idx_start] + AR_BLOCK + ar_section[idx_end:]
new_content = content[:ar_start] + new_ar_section + content[zh_start:]

with open(path, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Done. AR replaced.")
